#pragma once
#include <Windows.h>
#include <wincodec.h>
#include <shlobj_core.h>
#include <shlwapi.h>
//#include "Functions.h"
#define QKINI_ERR                           0
#define QKINI_NEWFILE                       1
#define QKINI_NORMAL                        2

typedef struct QKINIDESC
{
    int iType;
    PWSTR pszContent;
    HANDLE hFile;
    DWORD dwSize;
}*HQKINI;


PWSTR StrRStrW(PCWSTR lpSource, PCWSTR lpLast, PCWSTR lpSrch);
PWSTR QKINIReadString2(HQKINI hINI, PCWSTR pszSectionName, PCWSTR pszKeyName, PCWSTR pszDefStr);



struct CAppLang {
    LPWSTR LANG_ID_INFO_ENGLISH;
    LPWSTR LANG_ID_INFO_OWNLANG;
    LPWSTR LANG_ID_INFO_MACHINE;
    LPWSTR LANG_ID_INFO_BY;
    LPWSTR LANG_ID_INFO_WARN;
    LPWSTR LANG_ID_INFO_WARNOWN;
    LPWSTR LANG_ID_GLOBAL_HAVENTDONE;
    LPWSTR LANG_ID_STARTUP_TITLE;
    LPWSTR LANG_ID_STARTUP_OPENFILE;
    LPWSTR LANG_ID_STARTUP_OPENFOLDER;
    LPWSTR LANG_ID_STARTUP_RECENTLY;
    LPWSTR LANG_ID_STARTUP_ONLYFORTEST;
    LPWSTR LANG_ID_STARTUP_EVALUATIONCOPY;
    LPWSTR LANG_ID_OPENFILE_FILE;
    LPWSTR LANG_ID_OPENFILE_FOLDER;
    LPWSTR LANG_ID_MAIN_LIST;
    LPWSTR LANG_ID_MAIN_ADD;
    LPWSTR LANG_ID_MAIN_DEL;
    LPWSTR LANG_ID_MAIN_OPENFILE;
    LPWSTR LANG_ID_MAIN_OPENFOLDER;
    LPWSTR LANG_ID_MAIN_OPENONLINE;
    LPWSTR LANG_ID_MAIN_SAVECOVER;
    LPWSTR LANG_ID_MAIN_EMPTYLIST;
    LPWSTR LANG_ID_MAIN_EMPTYLRC;
    LPWSTR LANG_ID_LISTMENU_PLAY;
    LPWSTR LANG_ID_LISTMENU_REMOVE;
    LPWSTR LANG_ID_LISTMENU_SPEED;
    LPWSTR LANG_ID_SETTINGS_TITLE;
    LPWSTR LANG_ID_SETTINGS_APPEARANCE;
    LPWSTR LANG_ID_SETTINGS_THEME;
    LPWSTR LANG_ID_SETTINGS_SYSNORMAL;
    LPWSTR LANG_ID_SETTINGS_LIGHT;
    LPWSTR LANG_ID_SETTINGS_DARK;
    LPWSTR LANG_ID_SETTINGS_BACK;
    LPWSTR LANG_ID_SETTINGS_BACKMATERIAL;
    LPWSTR LANG_ID_SETTINGS_ACRYLIC;
    LPWSTR LANG_ID_SETTINGS_MICA;
    LPWSTR LANG_ID_SETTINGS_UPDATE;
    LPWSTR LANG_ID_SETTINGS_CHECKING;
    LPWSTR LANG_ID_SETTINGS_NONEW;
    LPWSTR LANG_ID_SETTINGS_NEW;
    LPWSTR LANG_ID_SETTINGS_RESTART;
    LPWSTR LANG_ID_SETTINGS_DOWNLOAD;
    LPWSTR LANG_ID_SETTINGS_DOWNLOADPROGRESS;
    LPWSTR LANG_ID_SETTINGS_RESTARTBTN;
    LPWSTR LANG_ID_SETTINGS_UPDATEBTN;
    LPWSTR LANG_ID_SETTINGS_CURRENTVER;
    LPWSTR LANG_ID_SETTINGS_NEWVER;
    LPWSTR LANG_ID_SETTINGS_ABOUT;
    LPWSTR LANG_ID_SETTINGS_DETAIL;
    LPWSTR LANG_ID_SETTINGS_LANGUAGE;
    LPWSTR LANG_ID_SETTINGS_APPLY;
    LPWSTR LANG_ID_PLAYLIST_TITLE;
    LPWSTR LANG_ID_PLAYLIST_ITEMS;
    LPWSTR LANG_ID_PLAYLIST_PLAY;
    LPWSTR LANG_ID_PLAYLIST_ADDFILE;
    LPWSTR LANG_ID_PLAYLIST_LOCATE;
    LPWSTR LANG_ID_PLAYLIST_PLAYLIST;
    LPWSTR LANG_ID_PLAYLIST_UNKNOWNARTIST;
    LPWSTR LANG_ID_PLAYLIST_UNKNOWNALBUM;
    LPWSTR LANG_ID_PLAYLIST_SEARCHLIST;
    LPWSTR LANG_ID_PLAYLIST_SEARCHSONG;
    LPWSTR LANG_ID_EFFECT_TITLE;
    LPWSTR LANG_ID_PLUGIN_TITLE;
    LPWSTR LANG_ID_PLUGIN_LIST;
    LPWSTR LANG_ID_OOBE_WELCOME;
    LPWSTR LANG_ID_OOBE_CONTINUE;
    LPWSTR LANG_ID_OOBE_LANG;
};

CAppLang readLang(PCWSTR Path);